server:
  port: ${SERVER_PORT:3001}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/timecalcdb}
    username: ${SPRING_DATASOURCE_USERNAME:timecalcuser}
    password: ${SPRING_DATASOURCE_PASSWORD:taskcalcpass}
  flyway:
    enabled: true
    locations: classpath:db/migration
